# Generated by Django 3.2.7 on 2021-11-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100000)),
                ('end1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end1', to='portal.person')),
                ('end2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end2', to='portal.person')),
            ],
        ),
    ]
