# Generated by Django 3.2.7 on 2021-11-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.CharField(max_length=100000),
        ),
    ]
