# Generated by Django 3.2.7 on 2021-11-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_chat_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='chat_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
