# Generated by Django 3.2.7 on 2021-11-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20211127_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='chat_content',
            field=models.TextField(max_length=100000, null=True),
        ),
    ]
