# Generated by Django 3.2.7 on 2021-11-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_course_chat_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='chat_content',
            field=models.TextField(default='', max_length=100000),
        ),
    ]
