# Generated by Django 3.2.7 on 2021-11-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_course_chat_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='create_ta_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='mem_ta_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
