# Generated by Django 3.2.7 on 2021-11-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20211127_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
